spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sandbox_db
spring.datasource.username=sandbox_user
spring.datasource.password=sandbox_pass
spring.jpa.hibernate.ddl-auto=update
